export const companyConstants = {
	
	COMPANY_ADD_REQUEST: "COMPANY_ADD_REQUEST",
	COMPANY_ADD_FAILURE: "COMPANY_ADD_FAILURE",
	COMPANY_ADD_SUCCESS: "COMPANY_ADD_SUCCESS",

	
	COMPANY_REQUEST_REMOVE_REQUEST: "COMPANY_REQUEST_REMOVE_REQUEST",
	COMPANY_REQUEST_REMOVE_SUCCESS: "COMPANY_REQUEST_REMOVE_SUCCESS",
	COMPANY_REQUEST_REMOVE_FAILURE: "COMPANY_REQUEST_REMOVE_FAILURE",
	
	HIDE_REQUEST_MODAL: "HIDE_REQUEST_MODAL",

	COMPANIES_GET_REQUEST: "COMPANIES_GET_REQUEST",
	COMPANIES_GET_FAILURE: "COMPANIES_GET_FAILURE",
	COMPANIES_GET_SUCCESS: "COMPANIES_GET_SUCCESS",
	
	COMPANY_HIDE_SUCCESS:"COMPANY_HIDE_SUCCESS",
	COMPANY_HIDE_FAIL: "COMPANY_HIDE_FAIL",


	COMPANIES_REMOVE_REQUEST: "COMPANIES_REMOVE_REQUEST",
	COMPANIES_REMOVE_SUCCESS: "COMPANIES_REMOVE_SUCCESS",
	COMPANIES_REMOVE_FAILURE: "COMPANIES_REMOVE_FAILURE",
	
	COMPANIES_REMOVE_REQUEST_ARRAY:"COMPANIES_REMOVE_REQUEST_ARRAY",
	
	HIDE_ADD_COMPANY_MODAL: "HIDE_ADD_COMPANY_MODAL",
	SHOW_ADD_COMPANY_MODAL: "SHOW_ADD_COMPANY_MODAL",

	COMPANY_SUBMIT_SUCCESS:"COMPANY_SUBMIT_SUCCESS",
	COMPANY_SUBMIT_FAILURE:"COMPANY_SUBMIT_FAILURE",
	COMPANY_SUBMIT_REQUEST:"COMPANY_SUBMIT_REQUEST",

	HIDE_MODAL_INFO: "HIDE_MODAL_INFO",
};
