export const roleConstants = {
	
	ROLE_ADD_REQUEST: "ROLE_ADD_REQUEST",
	ROLE_ADD_FAILURE: "ROLE_ADD_FAILURE",
	ROLE_ADD_SUCCESS: "ROLE_ADD_SUCCESS",

	
	ROLE_REQUEST_REMOVE_REQUEST: "ROLE_REQUEST_REMOVE_REQUEST",
	ROLE_REQUEST_REMOVE_SUCCESS: "ROLE_REQUEST_REMOVE_SUCCESS",
	ROLE_REQUEST_REMOVE_FAILURE: "ROLE_REQUEST_REMOVE_FAILURE",
	
	HIDE_REQUEST_MODAL: "HIDE_REQUEST_MODAL",

	ROLES_GET_REQUEST: "ROLES_GET_REQUEST",
	ROLES_GET_FAILURE: "ROLES_GET_FAILURE",
	ROLES_GET_SUCCESS: "ROLES_GET_SUCCESS",
	
	ROLE_HIDE_SUCCESS:"ROLE_HIDE_SUCCESS",
	ROLE_HIDE_FAIL: "ROLE_HIDE_FAIL",


	ROLES_REMOVE_REQUEST: "ROLES_REMOVE_REQUEST",
	ROLES_REMOVE_SUCCESS: "ROLES_REMOVE_SUCCESS",
	ROLES_REMOVE_FAILURE: "ROLES_REMOVE_FAILURE",
	
	ROLES_REMOVE_REQUEST_ARRAY:"ROLES_REMOVE_REQUEST_ARRAY",
	
	HIDE_ADD_ROLE_MODAL: "HIDE_ADD_ROLE_MODAL",
	SHOW_ADD_ROLE_MODAL: "SHOW_ADD_ROLE_MODAL",

	ROLE_SUBMIT_SUCCESS:"ROLE_SUBMIT_SUCCESS",
	ROLE_SUBMIT_FAILURE:"ROLE_SUBMIT_FAILURE",
	ROLE_SUBMIT_REQUEST:"ROLE_SUBMIT_REQUEST",

	HIDE_MODAL_INFO: "HIDE_MODAL_INFO",
};
