export const taskConstants = {
	

	SET_TASK_REQUEST: "SET_TASK_REQUEST",
	SET_TASK_SUCCESS: "SET_TASK_SUCCESS",
	SET_TASK_FAILURE: "SET_TASK_FAILURE",

	
	HIDE_EDIT_TASK_MODAL: "HIDE_EDIT_TASK_MODAL",
	SHOW_EDIT_TASK_MODAL: "SHOW_EDIT_TASK_MODAL",

	DOCUMENT_HIDE_MODAL: "DOCUMENT_HIDE_MODAL",

	TASK_SET_REQUEST: "TASK_SET_REQUEST",
	TASK_SET_SUCCESS: "TASK_SET_SUCCESS",
	TASK_SET_FAILURE: "TASK_SET_FAILURE",
};
